spring:
  application:
    name: m20-spring-security-authentication
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/m20springsecurityauthenticationdb
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 9090